export const userData = [
  {
    name: "Январь",
    "Active User": 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Февраль",
    "Active User": 3000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Март",
    "Active User": 5000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Апрель",
    "Active User": 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Май",
    "Active User": 3000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Июнь",
    "Active User": 2000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Июль",
    "Active User": 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Август",
    "Active User": 3000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Сентябрь",
    "Active User": 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Октябрь",
    "Active User": 1000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Ноябрь",
    "Active User": 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Декабрь",
    "Active User": 3000,
    pv: 2400,
    amt: 2400,
  },
];

export const productData = [
  {
    name: "Январь",
    Sales: 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Февраль",
    Sales: 3000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Март",
    Sales: 5000,
    pv: 2400,
    amt: 2400,
  },
];

export const userRows = [
  {
    id: 1,
    username: "Джон Сноу",
    avatar: "http://unsplash.it/45/45",
    email: "john.snow@mail.ru",
    status: "actived",
    transaction: "2499р.",
  },
  {
    id: 2,
    username: "Джон Сноу",
    avatar: "http://unsplash.it/45/45",
    email: "john.snow@mail.ru",
    status: "actived",
    transaction: "2499р.",
  },
  {
    id: 3,
    username: "Джон Сноу",
    avatar: "http://unsplash.it/45/45",
    email: "john.snow@mail.ru",
    status: "actived",
    transaction: "2499р.",
  },
  {
    id: 4,
    username: "Джон Сноу",
    avatar: "http://unsplash.it/45/45",
    email: "john.snow@mail.ru",
    status: "actived",
    transaction: "2499р.",
  },
  {
    id: 5,
    username: "Джон Сноу",
    avatar: "http://unsplash.it/45/45",
    email: "john.snow@mail.ru",
    status: "actived",
    transaction: "2499р.",
  },
  {
    id: 6,
    username: "Джон Сноу",
    avatar: "http://unsplash.it/45/45",
    email: "john.snow@mail.ru",
    status: "actived",
    transaction: "2499р.",
  },
  {
    id: 7,
    username: "Джон Сноу",
    avatar: "http://unsplash.it/45/45",
    email: "john.snow@mail.ru",
    status: "actived",
    transaction: "2499р.",
  },
  {
    id: 8,
    username: "Джон Сноу",
    avatar: "http://unsplash.it/45/45",
    email: "john.snow@mail.ru",
    status: "actived",
    transaction: "2499р.",
  },
  {
    id: 9,
    username: "Джон Сноу",
    avatar: "http://unsplash.it/45/45",
    email: "john.snow@mail.ru",
    status: "actived",
    transaction: "2499р.",
  },
  {
    id: 10,
    username: "Джон Сноу",
    avatar: "http://unsplash.it/45/45",
    email: "john.snow@mail.ru",
    status: "actived",
    transaction: "2499р.",
  },
];

export const productRows = [
  {
    id: 1,
    name: "T-Shirts",
    img: "http://unsplash.it/45/45",
    stock: 123,
    status: "actived",
    price: "2499р.",
  },
  {
    id: 2,
    name: "T-Shirts",
    img: "http://unsplash.it/45/45",
    stock: 123,
    status: "actived",
    price: "2499р.",
  },
  {
    id: 3,
    name: "T-Shirts",
    img: "http://unsplash.it/45/45",
    stock: 123,
    status: "actived",
    price: "2499р.",
  },
  {
    id: 4,
    name: "T-Shirts",
    img: "http://unsplash.it/45/45",
    stock: 123,
    status: "actived",
    price: "2499р.",
  },
  {
    id: 5,
    name: "T-Shirts",
    img: "http://unsplash.it/45/45",
    stock: 123,
    status: "actived",
    price: "2499р.",
  },
  {
    id: 6,
    name: "T-Shirts",
    img: "http://unsplash.it/45/45",
    stock: 123,
    status: "actived",
    price: "2499р.",
  },
  {
    id: 7,
    name: "T-Shirts",
    img: "http://unsplash.it/45/45",
    stock: 123,
    status: "actived",
    price: "2499р.",
  },
  {
    id: 8,
    name: "T-Shirts",
    img: "http://unsplash.it/45/45",
    stock: 123,
    status: "actived",
    price: "2499р.",
  },
  {
    id: 9,
    name: "T-Shirts",
    img: "http://unsplash.it/45/45",
    stock: 123,
    status: "actived",
    price: "2499р.",
  },
  {
    id: 10,
    name: "T-Shirts",
    img: "http://unsplash.it/45/45",
    stock: 123,
    status: "actived",
    price: "2499р.",
  },
];
